# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-ios

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: |
            ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn jest

      - name: Run unit tests
        run: yarn test


      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install Ruby dependencies
        run: bundle install

      - name: Build app with Fastlane
        run: bundle exec fastlane build
        working-directory: ios
