# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-ios

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: |
            ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn jest --coverage --coverageReporters json-summary

      # - name: Jest Coverage Comment
      #   id: coverageComment
      #   uses: MishaKav/jest-coverage-comment@main
      #   with:
      #     # hide-comment: true
      #     # coverage-summary-path: ./coverage-summary.json
      #     coverage-summary-path: ./coverage/coverage-summary.json
      #     title: Coverage
      #     summary-title: Current coverage
      #     badge-title: Coverage
      #     hide-comment: false
      #     create-new-comment: false
      #     hide-summary: false
      #     coverage-title: Current coverage
      #     coverage-path: ./coverage.txt`
      
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Coverage Comment
          summary-title: Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          coverage-title: Coverage
          coverage-path: ./coverage.txt    

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"


      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install Ruby dependencies
        run: bundle install

      - name: Build app with Fastlane
        run: bundle exec fastlane build
        working-directory: ios
