# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-ios

on:
  pull_request:
    branches: [ 'dev' ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout to repository
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1

      - name: Install Ruby dependencies
        run: bundle install
        working-directory: ios

      - name: Install Pods
        run: pod install --repo-update
        working-directory: ios

      - name: Build app with Fastlane
        run: bundle exec fastlane build
        working-directory: ios
