# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-ios

on:
  pull_request:
    branches: [ 'dev' ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install Ruby dependencies
        run: bundle install

      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: |
            ios/Pods
            ios/.rugby/build
            ios/.rugby/cache.yml
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Install Pods
        if: steps.podcache.outputs.cache-hit != 'true'
        run: bundle exec pod install && rugby plans --plan ci
        working-directory: ios

      - name: Get is Podfile.lock changed
        id: changed-files-specific
        if: steps.podcache.outputs.cache-hit != 'true'
        uses: tj-actions/changed-files@v35
        with:
          files: ios/Podfile.lock

      - name: Exit job if Podfile.lock is not synced
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: exit 1

      - name: Difference between Podfile.lock and Manifest.lock
        run: diff Podfile.lock Pods/Manifest.lock
        working-directory: ios

      - name: Install Rugby
        if: steps.podcache.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/swiftyfinch/Rugby/releases/download/1.22.0/rugby.zip
          unzip rugby.zip
          mkdir -p /usr/local/bin && cp rugby/bin/rugby /usr/local/bin

      - name: Build Pods
        if: steps.podcache.outputs.cache-hit != 'true'
        run: rugby plans --plan ci
        working-directory: ios

      - name: Run unit tests
        run: yarn test

      - name: Build app with Fastlane
        run: bundle exec fastlane build
        working-directory: ios
