# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-ios

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: |
            ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn jest --coverage --coverageReporters json-summary --watchAll

      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          # hide-comment: true
          # coverage-summary-path: ./coverage-summary.json
          title: Coverage
          summary-title: Current coverage
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          coverage-title: Current coverage
          coverage-path: ./coverage.txt

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

      # - name: Save report
      #   # run: mkdir -p path/to/artifact
      #   # run: echo hello > coverage.txt
      #   run: |
      #     echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}" > coverage.txt
      #     echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}" > coverage.txt
      #     echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}" > coverage.txt
        # uses: actions/upload-artifact@master
        # with:
        #   name: my-artifact
        #   path: path/to/artifact

      # - name: Create the badge
      #   # if: github.ref == 'refs/heads/main'
      #   uses: schneegans/dynamic-badges-action@v1.6.0
      #   with:
      #     auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
      #     gistID: 5e90d640f8c212ab7bbac38f72323f80
      #     filename: jest-coverage-comment__main.json
      #     label: coverage
      #     message: ${{ steps.coverageComment.outputs.coverage }}%
      #     color: ${{ steps.coverageComment.outputs.color }}
      #     namedLogo: javascript

      - name: Update README with Coverage HTML
        # if: github.ref == 'refs/heads/main'
        run: |
          sed -i '/<!-- Jest Coverage Comment:Begin -->/,/<!-- Jest Coverage Comment:End -->/c\<!-- Jest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.summaryHtml }}\n<!-- Jest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes in README
        # if: github.ref == 'refs/heads/test/coverage'
        uses: actions-js/push@master
        with:
          message: Update coverage in README
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install Ruby dependencies
        run: bundle install

      - name: Build app with Fastlane
        run: bundle exec fastlane build
        working-directory: ios
